bold = "assets/fonts/IBMPlexMono-Bold.ttf"
bold_italic = "assets/fonts/IBMPlexMono-BoldItalic.ttf"
extra_light = "assets/fonts/IBMPlexMono-ExtraLight.ttf"
extra_light_italic = "assets/fonts/IBMPlexMono-ExtraLightItalic.ttf"
italic = "assets/fonts/IBMPlexMono-Italic.ttf"
light = "assets/fonts/IBMPlexMono-Light.ttf"
light_italic = "assets/fonts/IBMPlexMono-LightItalic.ttf"
medium = "assets/fonts/IBMPlexMono-Medium.ttf"
medium_italic = "assets/fonts/IBMPlexMono-MediumItalic.ttf"
regular = "assets/fonts/IBMPlexMono-Regular.ttf"
semibold = "assets/fonts/IBMPlexMono-SemiBold.ttf"
semibold_italic = "assets/fonts/IBMPlexMono-SemiBoldItalic.ttf"
thin = "assets/fonts/IBMPlexMono-Thin.ttf"
thin_italic = "assets/fonts/IBMPlexMono-ThinItalic.ttf"
arcade = "assets/fonts/JoystixMonospace.ttf"